//go:build postgresql

package revenue

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"

	"google.golang.org/protobuf/encoding/protojson"

	postgresCore "github.com/erniealice/espyna-golang/contrib/postgres/internal/adapter/core"
	interfaces "github.com/erniealice/espyna-golang/database/interfaces"
	"github.com/erniealice/espyna-golang/registry"
	entityid "github.com/erniealice/espyna-golang/registry/entityid"
	revenuetaxlinepb "github.com/erniealice/esqyma/pkg/schema/v1/domain/revenue/revenue_tax_line"
)

func init() {
	registry.RegisterRepositoryFactory("postgresql", entityid.RevenueTaxLine, func(conn any, tableName string) (any, error) {
		db, ok := conn.(*sql.DB)
		if !ok {
			return nil, fmt.Errorf("postgres revenue_tax_line repository requires *sql.DB, got %T", conn)
		}
		dbOps := postgresCore.NewWorkspaceAwareOperations(db)
		return NewPostgresRevenueTaxLineRepository(db, dbOps, tableName), nil
	})
}

// PostgresRevenueTaxLineRepository implements revenue_tax_line operations using PostgreSQL.
// RevenueTaxLine is system-generated by ComputeTaxesForRevenue — no public create/update/delete.
type PostgresRevenueTaxLineRepository struct {
	revenuetaxlinepb.UnimplementedRevenueTaxLineDomainServiceServer
	dbOps     interfaces.DatabaseOperation
	db        *sql.DB
	tableName string
}

// NewPostgresRevenueTaxLineRepository creates a new PostgreSQL revenue_tax_line repository.
func NewPostgresRevenueTaxLineRepository(db *sql.DB, dbOps interfaces.DatabaseOperation, tableName string) revenuetaxlinepb.RevenueTaxLineDomainServiceServer {
	if tableName == "" {
		tableName = entityid.RevenueTaxLine
	}
	return &PostgresRevenueTaxLineRepository{
		dbOps:     dbOps,
		db:        db,
		tableName: tableName,
	}
}

func unmarshalRevenueTaxLine(raw map[string]any) (*revenuetaxlinepb.RevenueTaxLine, error) {
	js, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal raw: %w", err)
	}
	r := &revenuetaxlinepb.RevenueTaxLine{}
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(js, r); err != nil {
		return nil, fmt.Errorf("unmarshal proto: %w", err)
	}
	return r, nil
}

// ReadRevenueTaxLine retrieves a revenue_tax_line record by ID.
func (r *PostgresRevenueTaxLineRepository) ReadRevenueTaxLine(ctx context.Context, req *revenuetaxlinepb.ReadRevenueTaxLineRequest) (*revenuetaxlinepb.ReadRevenueTaxLineResponse, error) {
	if req == nil || req.Data == nil || req.Data.Id == "" {
		return nil, fmt.Errorf("revenue_tax_line ID is required")
	}
	result, err := r.dbOps.Read(ctx, r.tableName, req.Data.Id)
	if err != nil {
		return nil, fmt.Errorf("failed to read revenue_tax_line: %w", err)
	}
	line, err := unmarshalRevenueTaxLine(result)
	if err != nil {
		return nil, err
	}
	return &revenuetaxlinepb.ReadRevenueTaxLineResponse{Success: true, Data: []*revenuetaxlinepb.RevenueTaxLine{line}}, nil
}

// ListRevenueTaxLines lists revenue_tax_line records.
func (r *PostgresRevenueTaxLineRepository) ListRevenueTaxLines(ctx context.Context, req *revenuetaxlinepb.ListRevenueTaxLinesRequest) (*revenuetaxlinepb.ListRevenueTaxLinesResponse, error) {
	var params *interfaces.ListParams
	if req != nil && req.Filters != nil {
		params = &interfaces.ListParams{Filters: req.Filters}
	}
	listResult, err := r.dbOps.List(ctx, r.tableName, params)
	if err != nil {
		return nil, fmt.Errorf("failed to list revenue_tax_lines: %w", err)
	}
	var items []*revenuetaxlinepb.RevenueTaxLine
	for _, raw := range listResult.Data {
		line, err := unmarshalRevenueTaxLine(raw)
		if err != nil {
			log.Printf("WARN: unmarshal revenue_tax_line: %v", err)
			continue
		}
		items = append(items, line)
	}
	return &revenuetaxlinepb.ListRevenueTaxLinesResponse{Success: true, Data: items}, nil
}

// RevenueTaxLineQueries provides system-write operations used by ComputeTaxesForRevenue.
type RevenueTaxLineQueries interface {
	// InsertForRevenue inserts a batch of revenue_tax_line rows for a revenue.
	// Called within the compute use case after DeleteByRevenueID for idempotency.
	InsertForRevenue(ctx context.Context, lines []*revenuetaxlinepb.RevenueTaxLine) error
	// DeleteByRevenueID deletes all revenue_tax_line rows for a given revenue_id.
	// Called before InsertForRevenue within a transaction for idempotency.
	DeleteByRevenueID(ctx context.Context, revenueID string) error
	// ListByRevenueID returns all revenue_tax_line rows for a given revenue_id.
	ListByRevenueID(ctx context.Context, revenueID string) ([]*revenuetaxlinepb.RevenueTaxLine, error)
}

// InsertForRevenue inserts a batch of revenue_tax_line rows.
func (r *PostgresRevenueTaxLineRepository) InsertForRevenue(ctx context.Context, lines []*revenuetaxlinepb.RevenueTaxLine) error {
	for _, line := range lines {
		jsonData, err := protojson.Marshal(line)
		if err != nil {
			return fmt.Errorf("marshal line: %w", err)
		}
		var data map[string]any
		if err := json.Unmarshal(jsonData, &data); err != nil {
			return fmt.Errorf("unmarshal to map: %w", err)
		}
		if _, err := r.dbOps.Create(ctx, r.tableName, data); err != nil {
			return fmt.Errorf("insert revenue_tax_line: %w", err)
		}
	}
	return nil
}

// DeleteByRevenueID deletes all revenue_tax_line rows for a revenue_id.
func (r *PostgresRevenueTaxLineRepository) DeleteByRevenueID(ctx context.Context, revenueID string) error {
	if r.db == nil {
		return fmt.Errorf("DeleteByRevenueID requires raw *sql.DB")
	}
	// Hoisted into the sanctioned core write funnel (P2 Phase-3 Q-WRITE-PREPARE).
	// HardDeleteByColumn emits the byte-equivalent
	// "DELETE FROM revenue_tax_line WHERE revenue_id = $1".
	if _, err := postgresCore.HardDeleteByColumn(ctx, r.db, "revenue_tax_line", "revenue_id", revenueID); err != nil {
		return fmt.Errorf("DeleteByRevenueID: %w", err)
	}
	return nil
}

// ListByRevenueID returns all revenue_tax_line rows for a given revenue_id.
func (r *PostgresRevenueTaxLineRepository) ListByRevenueID(ctx context.Context, revenueID string) ([]*revenuetaxlinepb.RevenueTaxLine, error) {
	if r.db == nil {
		return nil, fmt.Errorf("ListByRevenueID requires raw *sql.DB")
	}
	rows, err := r.db.QueryContext(ctx,
		`SELECT row_to_json(rtl) FROM revenue_tax_line rtl
		 WHERE rtl.revenue_id = $1
		 ORDER BY rtl.direction, rtl.tax_kind_snapshot`,
		revenueID,
	)
	if err != nil {
		return nil, fmt.Errorf("ListByRevenueID query: %w", err)
	}
	defer rows.Close()

	var items []*revenuetaxlinepb.RevenueTaxLine
	for rows.Next() {
		var rawJSON []byte
		if err := rows.Scan(&rawJSON); err != nil {
			return nil, fmt.Errorf("ListByRevenueID scan: %w", err)
		}
		line := &revenuetaxlinepb.RevenueTaxLine{}
		if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(rawJSON, line); err != nil {
			log.Printf("WARN: ListByRevenueID unmarshal: %v", err)
			continue
		}
		items = append(items, line)
	}
	return items, rows.Err()
}

// Compile-time interface check.
var _ RevenueTaxLineQueries = (*PostgresRevenueTaxLineRepository)(nil)

// helper to suppress unused import — removed if not needed
var _ = sql.ErrNoRows
