//go:build mysql

// Dialect translation from postgres gold standard:
//   - $1 → ? (MySQL positional placeholders)
//   - row_to_json(rtl) → explicit column SELECT with JSON_OBJECT
//     (MySQL has no row_to_json; instead we do a plain SELECT and marshal
//     the scanned columns as a map for protojson round-trip)
//   - DELETE FROM ... WHERE revenue_id = $1 → DELETE FROM ... WHERE revenue_id = ?
//   - ORDER BY direction, tax_kind_snapshot stays
//
// RevenueTaxLine is system-generated by ComputeTaxesForRevenue — no public
// create/update/delete via RPC.
package revenue

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"log"

	"google.golang.org/protobuf/encoding/protojson"

	mysqlCore "github.com/erniealice/espyna-golang/contrib/mysql/internal/adapter/core"
	interfaces "github.com/erniealice/espyna-golang/shared/database/interfaces"
	"github.com/erniealice/espyna-golang/registry"
	entityid "github.com/erniealice/espyna-golang/registry/entityid"
	revenuetaxlinepb "github.com/erniealice/esqyma/pkg/schema/v1/domain/revenue/revenue_tax_line"
)

func init() {
	registry.RegisterRepositoryFactory("mysql", entityid.RevenueTaxLine, func(conn any, tableName string) (any, error) {
		db, ok := conn.(*sql.DB)
		if !ok {
			return nil, fmt.Errorf("mysql revenue_tax_line repository requires *sql.DB, got %T", conn)
		}
		dbOps := mysqlCore.NewWorkspaceAwareOperations(db)
		return NewMySQLRevenueTaxLineRepository(db, dbOps, tableName), nil
	})
}

// MySQLRevenueTaxLineRepository implements revenue_tax_line operations using MySQL 8.0+.
type MySQLRevenueTaxLineRepository struct {
	revenuetaxlinepb.UnimplementedRevenueTaxLineDomainServiceServer
	dbOps     interfaces.DatabaseOperation
	db        *sql.DB
	tableName string
}

// NewMySQLRevenueTaxLineRepository creates a new MySQL revenue_tax_line repository.
func NewMySQLRevenueTaxLineRepository(db *sql.DB, dbOps interfaces.DatabaseOperation, tableName string) revenuetaxlinepb.RevenueTaxLineDomainServiceServer {
	if tableName == "" {
		tableName = entityid.RevenueTaxLine
	}
	return &MySQLRevenueTaxLineRepository{
		dbOps:     dbOps,
		db:        db,
		tableName: tableName,
	}
}

func unmarshalRevenueTaxLine(raw map[string]any) (*revenuetaxlinepb.RevenueTaxLine, error) {
	js, err := json.Marshal(raw)
	if err != nil {
		return nil, fmt.Errorf("marshal raw: %w", err)
	}
	r := &revenuetaxlinepb.RevenueTaxLine{}
	if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(js, r); err != nil {
		return nil, fmt.Errorf("unmarshal proto: %w", err)
	}
	return r, nil
}

// ReadRevenueTaxLine retrieves a revenue_tax_line record by ID.
func (r *MySQLRevenueTaxLineRepository) ReadRevenueTaxLine(ctx context.Context, req *revenuetaxlinepb.ReadRevenueTaxLineRequest) (*revenuetaxlinepb.ReadRevenueTaxLineResponse, error) {
	if req == nil || req.Data == nil || req.Data.Id == "" {
		return nil, fmt.Errorf("revenue_tax_line ID is required")
	}
	result, err := r.dbOps.Read(ctx, r.tableName, req.Data.Id)
	if err != nil {
		return nil, fmt.Errorf("failed to read revenue_tax_line: %w", err)
	}
	line, err := unmarshalRevenueTaxLine(mysqlCore.DenormalizeKeys(result))
	if err != nil {
		return nil, err
	}
	return &revenuetaxlinepb.ReadRevenueTaxLineResponse{Success: true, Data: []*revenuetaxlinepb.RevenueTaxLine{line}}, nil
}

// ListRevenueTaxLines lists revenue_tax_line records.
func (r *MySQLRevenueTaxLineRepository) ListRevenueTaxLines(ctx context.Context, req *revenuetaxlinepb.ListRevenueTaxLinesRequest) (*revenuetaxlinepb.ListRevenueTaxLinesResponse, error) {
	var params *interfaces.ListParams
	if req != nil && req.Filters != nil {
		params = &interfaces.ListParams{Filters: req.Filters}
	}
	listResult, err := r.dbOps.List(ctx, r.tableName, params)
	if err != nil {
		return nil, fmt.Errorf("failed to list revenue_tax_lines: %w", err)
	}
	var items []*revenuetaxlinepb.RevenueTaxLine
	for _, raw := range listResult.Data {
		line, err := unmarshalRevenueTaxLine(mysqlCore.DenormalizeKeys(raw))
		if err != nil {
			log.Printf("WARN: unmarshal revenue_tax_line: %v", err)
			continue
		}
		items = append(items, line)
	}
	return &revenuetaxlinepb.ListRevenueTaxLinesResponse{Success: true, Data: items}, nil
}

// RevenueTaxLineQueries provides system-write operations used by ComputeTaxesForRevenue.
type RevenueTaxLineQueries interface {
	InsertForRevenue(ctx context.Context, lines []*revenuetaxlinepb.RevenueTaxLine) error
	DeleteByRevenueID(ctx context.Context, revenueID string) error
	ListByRevenueID(ctx context.Context, revenueID string) ([]*revenuetaxlinepb.RevenueTaxLine, error)
}

// InsertForRevenue inserts a batch of revenue_tax_line rows.
func (r *MySQLRevenueTaxLineRepository) InsertForRevenue(ctx context.Context, lines []*revenuetaxlinepb.RevenueTaxLine) error {
	for _, line := range lines {
		jsonData, err := protojson.Marshal(line)
		if err != nil {
			return fmt.Errorf("marshal line: %w", err)
		}
		var data map[string]any
		if err := json.Unmarshal(jsonData, &data); err != nil {
			return fmt.Errorf("unmarshal to map: %w", err)
		}
		if _, err := r.dbOps.Create(ctx, r.tableName, data); err != nil {
			return fmt.Errorf("insert revenue_tax_line: %w", err)
		}
	}
	return nil
}

// DeleteByRevenueID deletes all revenue_tax_line rows for a revenue_id.
//
// Dialect: $1 → ?
func (r *MySQLRevenueTaxLineRepository) DeleteByRevenueID(ctx context.Context, revenueID string) error {
	if r.db == nil {
		return fmt.Errorf("DeleteByRevenueID requires raw *sql.DB")
	}
	_, err := r.db.ExecContext(ctx,
		"DELETE FROM `revenue_tax_line` WHERE `revenue_id` = ?",
		revenueID,
	)
	if err != nil {
		return fmt.Errorf("DeleteByRevenueID: %w", err)
	}
	return nil
}

// ListByRevenueID returns all revenue_tax_line rows for a given revenue_id.
//
// Dialect: row_to_json(rtl) → explicit column SELECT marshalled via DenormalizeKeys;
// $1 → ?; order stays.
func (r *MySQLRevenueTaxLineRepository) ListByRevenueID(ctx context.Context, revenueID string) ([]*revenuetaxlinepb.RevenueTaxLine, error) {
	if r.db == nil {
		return nil, fmt.Errorf("ListByRevenueID requires raw *sql.DB")
	}
	rows, err := r.db.QueryContext(ctx,
		"SELECT `id`, `revenue_id`, `direction`, `tax_kind_snapshot`, `rate_bps`, `base_amount`, `tax_amount`, `active`, `workspace_id`, `date_created`, `date_modified` FROM `revenue_tax_line` WHERE `revenue_id` = ? ORDER BY `direction`, `tax_kind_snapshot`",
		revenueID,
	)
	if err != nil {
		return nil, fmt.Errorf("ListByRevenueID query: %w", err)
	}
	defer rows.Close()

	var items []*revenuetaxlinepb.RevenueTaxLine
	for rows.Next() {
		var (
			id              string
			revID           string
			direction       *string
			taxKindSnapshot *string
			rateBps         *int64
			baseAmount      *int64
			taxAmount       *int64
			active          bool
			workspaceID     *string
			dateCreated     *string
			dateModified    *string
		)
		if err := rows.Scan(
			&id,
			&revID,
			&direction,
			&taxKindSnapshot,
			&rateBps,
			&baseAmount,
			&taxAmount,
			&active,
			&workspaceID,
			&dateCreated,
			&dateModified,
		); err != nil {
			return nil, fmt.Errorf("ListByRevenueID scan: %w", err)
		}
		raw := map[string]any{
			"id":         id,
			"revenue_id": revID,
			"active":     active,
		}
		if direction != nil {
			raw["direction"] = *direction
		}
		if taxKindSnapshot != nil {
			raw["tax_kind_snapshot"] = *taxKindSnapshot
		}
		if rateBps != nil {
			raw["rate_bps"] = *rateBps
		}
		if baseAmount != nil {
			raw["base_amount"] = *baseAmount
		}
		if taxAmount != nil {
			raw["tax_amount"] = *taxAmount
		}
		if workspaceID != nil {
			raw["workspace_id"] = *workspaceID
		}
		if dateCreated != nil {
			raw["date_created"] = *dateCreated
		}
		if dateModified != nil {
			raw["date_modified"] = *dateModified
		}
		line := &revenuetaxlinepb.RevenueTaxLine{}
		js, err := json.Marshal(mysqlCore.DenormalizeKeys(raw))
		if err != nil {
			log.Printf("WARN: ListByRevenueID marshal: %v", err)
			continue
		}
		if err := (protojson.UnmarshalOptions{DiscardUnknown: true}).Unmarshal(js, line); err != nil {
			log.Printf("WARN: ListByRevenueID unmarshal: %v", err)
			continue
		}
		items = append(items, line)
	}
	return items, rows.Err()
}

// Compile-time interface check.
var _ RevenueTaxLineQueries = (*MySQLRevenueTaxLineRepository)(nil)
