//go:build mock_db

package entity

import (
	"context"
	"fmt"
	"strconv"
	"sync"
	"time"

	datamock "leapfor.xyz/copya/golang"
	"github.com/erniealice/espyna-golang/internal/application/shared/listdata"
	"github.com/erniealice/espyna-golang/internal/infrastructure/registry"
	commonpb "github.com/erniealice/esqyma/pkg/schema/v1/domain/common"
	clientcategorypb "github.com/erniealice/esqyma/pkg/schema/v1/domain/entity/client_category"
)

// MockClientCategoryRepository implements entity.ClientCategoryRepository using stateful mock data
type MockClientCategoryRepository struct {
	clientcategorypb.UnimplementedClientCategoryDomainServiceServer
	businessType          string
	clientCategories      map[string]*clientcategorypb.ClientCategory // Store by simple ID
	clientCategoriesByKey map[string]*clientcategorypb.ClientCategory // Store by composite key (clientId-categoryId)
	mutex                 sync.RWMutex                                // Thread-safe concurrent access
	initialized           bool                                        // Prevent double initialization
	processor             *listdata.ListDataProcessor                // List data processing for pagination, filtering, sorting
}

// ClientCategoryRepositoryOption allows configuration of repository behavior
type ClientCategoryRepositoryOption func(*MockClientCategoryRepository)

// WithClientCategoryTestOptimizations enables test-specific optimizations
func WithClientCategoryTestOptimizations(enabled bool) ClientCategoryRepositoryOption {
	return func(r *MockClientCategoryRepository) {
		// Test optimizations could include faster ID generation, logging, etc.
		// For now, this is a placeholder for future optimizations
	}
}

// NewMockClientCategoryRepository creates a new mock client_category repository
func NewMockClientCategoryRepository(businessType string, options ...ClientCategoryRepositoryOption) clientcategorypb.ClientCategoryDomainServiceServer {
	if businessType == "" {
		businessType = "education" // Default fallback
	}

	repo := &MockClientCategoryRepository{
		businessType:          businessType,
		clientCategories:      make(map[string]*clientcategorypb.ClientCategory),
		clientCategoriesByKey: make(map[string]*clientcategorypb.ClientCategory),
		processor:             listdata.NewListDataProcessor(),
	}

	// Apply optional configurations
	for _, option := range options {
		option(repo)
	}

	// Initialize with mock data once
	if err := repo.loadInitialData(); err != nil {
		// Log error but don't fail - allows graceful degradation
		fmt.Printf("Warning: Failed to load initial mock data: %v\n", err)
	}

	return repo
}

// loadInitialData loads mock data from the copya package
func (r *MockClientCategoryRepository) loadInitialData() error {
	r.mutex.Lock()
	defer r.mutex.Unlock()

	if r.initialized {
		return nil // Prevent double initialization
	}

	// Load from @leapfor/copya package
	rawClientCategories, err := datamock.LoadClientCategories(r.businessType)
	if err != nil {
		return fmt.Errorf("failed to load initial client categories: %w", err)
	}

	// Convert and store each client category in both maps
	for _, rawClientCategory := range rawClientCategories {
		if clientCategory, err := r.mapToProtobufClientCategory(rawClientCategory); err == nil {
			// Store by simple ID (for test compatibility)
			if clientCategory.Id != "" {
				r.clientCategories[clientCategory.Id] = clientCategory
			}
			// Store by composite key (for business logic)
			compositeKey := fmt.Sprintf("%s-%s", clientCategory.ClientId, clientCategory.CategoryId)
			r.clientCategoriesByKey[compositeKey] = clientCategory
		}
	}

	r.initialized = true
	return nil
}

// CreateClientCategory creates a new client_category with stateful storage
func (r *MockClientCategoryRepository) CreateClientCategory(ctx context.Context, req *clientcategorypb.CreateClientCategoryRequest) (*clientcategorypb.CreateClientCategoryResponse, error) {
	// Input validation
	if req == nil {
		return nil, fmt.Errorf("create client_category request is required")
	}
	if req.Data == nil {
		return nil, fmt.Errorf("client_category data is required")
	}
	if req.Data.ClientId == "" {
		return nil, fmt.Errorf("client_category clientId is required")
	}
	if req.Data.CategoryId == "" {
		return nil, fmt.Errorf("client_category categoryId is required")
	}

	r.mutex.Lock()
	defer r.mutex.Unlock()

	// Generate unique key with client and category IDs
	key := fmt.Sprintf("%s-%s", req.Data.ClientId, req.Data.CategoryId)

	// Check if already exists
	if _, exists := r.clientCategoriesByKey[key]; exists {
		return nil, fmt.Errorf("client_category with clientId '%s' and categoryId '%s' already exists", req.Data.ClientId, req.Data.CategoryId)
	}

	// Create new client_category preserving use case data
	newClientCategory := &clientcategorypb.ClientCategory{
		Id:          req.Data.Id, // Preserve ID generated by use case
		ClientId:    req.Data.ClientId,
		CategoryId:  req.Data.CategoryId,
		Active:      req.Data.Active, // Preserve active flag set by use case
		// Use timestamps from use case (correct millisecond units)
		DateCreated:        req.Data.DateCreated,
		DateCreatedString:  req.Data.DateCreatedString,
		DateModified:       req.Data.DateModified,
		DateModifiedString: req.Data.DateModifiedString,
	}

	// Copy nested Category object if provided (key fix for nested object preservation)
	if req.Data.Category != nil {
		newClientCategory.Category = req.Data.Category
	}

	// Store in both maps for dual access patterns
	if newClientCategory.Id != "" {
		r.clientCategories[newClientCategory.Id] = newClientCategory
	}
	r.clientCategoriesByKey[key] = newClientCategory

	return &clientcategorypb.CreateClientCategoryResponse{
		Data:    []*clientcategorypb.ClientCategory{newClientCategory},
		Success: true,
	}, nil
}

// ReadClientCategory retrieves a client_category by ID or by client ID and category ID from stateful storage
func (r *MockClientCategoryRepository) ReadClientCategory(ctx context.Context, req *clientcategorypb.ReadClientCategoryRequest) (*clientcategorypb.ReadClientCategoryResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("read client_category request is required")
	}
	if req.Data == nil {
		return nil, fmt.Errorf("client_category data is required")
	}

	r.mutex.RLock()
	defer r.mutex.RUnlock()

	var clientCategory *clientcategorypb.ClientCategory
	var exists bool

	// Try simple ID lookup first (for test compatibility)
	if req.Data.Id != "" {
		clientCategory, exists = r.clientCategories[req.Data.Id]
	}

	// Fallback to composite key lookup if simple ID not found or not provided
	if !exists && req.Data.ClientId != "" && req.Data.CategoryId != "" {
		compositeKey := fmt.Sprintf("%s-%s", req.Data.ClientId, req.Data.CategoryId)
		clientCategory, exists = r.clientCategoriesByKey[compositeKey]
	}

	// Return the found client_category
	if exists {
		return &clientcategorypb.ReadClientCategoryResponse{
			Data:    []*clientcategorypb.ClientCategory{clientCategory},
			Success: true,
		}, nil
	}

	// Return empty result for missing entity (no error)
	return &clientcategorypb.ReadClientCategoryResponse{
		Data:    []*clientcategorypb.ClientCategory{},
		Success: true,
	}, nil
}

// UpdateClientCategory updates an existing client_category in stateful storage
func (r *MockClientCategoryRepository) UpdateClientCategory(ctx context.Context, req *clientcategorypb.UpdateClientCategoryRequest) (*clientcategorypb.UpdateClientCategoryResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("update client_category request is required")
	}
	if req.Data == nil {
		return nil, fmt.Errorf("client_category data is required for update")
	}

	r.mutex.Lock()
	defer r.mutex.Unlock()

	var existingClientCategory *clientcategorypb.ClientCategory
	var exists bool
	var simpleKey string
	var compositeKey string

	// Try simple ID lookup first (for test compatibility)
	if req.Data.Id != "" {
		existingClientCategory, exists = r.clientCategories[req.Data.Id]
		simpleKey = req.Data.Id
	}

	// Fallback to composite key lookup
	if !exists && req.Data.ClientId != "" && req.Data.CategoryId != "" {
		compositeKey = fmt.Sprintf("%s-%s", req.Data.ClientId, req.Data.CategoryId)
		existingClientCategory, exists = r.clientCategoriesByKey[compositeKey]
	}

	if !exists {
		return nil, fmt.Errorf("client_category with client ID '%s' and category ID '%s' does not exist", req.Data.ClientId, req.Data.CategoryId)
	}

	// Update preserving use case timestamps and nested objects
	updatedClientCategory := &clientcategorypb.ClientCategory{
		Id:          req.Data.Id,
		ClientId:    req.Data.ClientId,
		CategoryId:  req.Data.CategoryId,
		Active:      req.Data.Active,
		// Preserve creation timestamps
		DateCreated:       existingClientCategory.DateCreated,
		DateCreatedString: existingClientCategory.DateCreatedString,
		// Use timestamps from use case (correct millisecond units)
		DateModified:       req.Data.DateModified,
		DateModifiedString: req.Data.DateModifiedString,
	}

	// Copy nested Category object if provided
	if req.Data.Category != nil {
		updatedClientCategory.Category = req.Data.Category
	} else {
		updatedClientCategory.Category = existingClientCategory.Category
	}

	// Update in both maps for dual access patterns
	if simpleKey != "" {
		r.clientCategories[simpleKey] = updatedClientCategory
	}
	if compositeKey == "" {
		compositeKey = fmt.Sprintf("%s-%s", updatedClientCategory.ClientId, updatedClientCategory.CategoryId)
	}
	r.clientCategoriesByKey[compositeKey] = updatedClientCategory

	return &clientcategorypb.UpdateClientCategoryResponse{
		Data:    []*clientcategorypb.ClientCategory{updatedClientCategory},
		Success: true,
	}, nil
}

// DeleteClientCategory deletes a client_category from stateful storage
func (r *MockClientCategoryRepository) DeleteClientCategory(ctx context.Context, req *clientcategorypb.DeleteClientCategoryRequest) (*clientcategorypb.DeleteClientCategoryResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("delete client_category request is required")
	}
	if req.Data == nil {
		return nil, fmt.Errorf("client_category data is required for deletion")
	}

	r.mutex.Lock()
	defer r.mutex.Unlock()

	var existingClientCategory *clientcategorypb.ClientCategory
	var exists bool
	var simpleKey string
	var compositeKey string

	// Try simple ID lookup first (for test compatibility)
	if req.Data.Id != "" {
		existingClientCategory, exists = r.clientCategories[req.Data.Id]
		simpleKey = req.Data.Id
		if exists {
			compositeKey = fmt.Sprintf("%s-%s", existingClientCategory.ClientId, existingClientCategory.CategoryId)
		}
	}

	// Fallback to composite key lookup
	if !exists && req.Data.ClientId != "" && req.Data.CategoryId != "" {
		compositeKey = fmt.Sprintf("%s-%s", req.Data.ClientId, req.Data.CategoryId)
		existingClientCategory, exists = r.clientCategoriesByKey[compositeKey]
		if exists {
			simpleKey = existingClientCategory.Id
		}
	}

	if !exists {
		return nil, fmt.Errorf("client_category with client ID '%s' and category ID '%s' does not exist", req.Data.ClientId, req.Data.CategoryId)
	}

	// Perform actual deletion from both persistent stores
	if simpleKey != "" {
		delete(r.clientCategories, simpleKey)
	}
	if compositeKey != "" {
		delete(r.clientCategoriesByKey, compositeKey)
	}

	return &clientcategorypb.DeleteClientCategoryResponse{
		Success: true,
	}, nil
}

// ListClientCategories retrieves all client_categories from stateful storage
func (r *MockClientCategoryRepository) ListClientCategories(ctx context.Context, req *clientcategorypb.ListClientCategoriesRequest) (*clientcategorypb.ListClientCategoriesResponse, error) {
	r.mutex.RLock()
	defer r.mutex.RUnlock()

	// Use composite key map as the authoritative source (avoids duplicates)
	clientCategories := make([]*clientcategorypb.ClientCategory, 0, len(r.clientCategoriesByKey))
	for _, clientCategory := range r.clientCategoriesByKey {
		clientCategories = append(clientCategories, clientCategory)
	}

	// Use the list data processor to handle filtering, sorting, searching, and pagination
	result, err := r.processor.ProcessListRequest(
		clientCategories,
		req.Pagination,
		req.Filters,
		req.Sort,
		req.Search,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to process client_category list data: %w", err)
	}

	// Convert processed items back to client_category protobuf format
	processedClientCategories := make([]*clientcategorypb.ClientCategory, len(result.Items))
	for i, item := range result.Items {
		if clientCategory, ok := item.(*clientcategorypb.ClientCategory); ok {
			processedClientCategories[i] = clientCategory
		} else {
			return nil, fmt.Errorf("failed to convert item to client_category type")
		}
	}

	return &clientcategorypb.ListClientCategoriesResponse{
		Data:    processedClientCategories,
		Success: true,
	}, nil
}

// GetClientCategoryListPageData retrieves client_categories with advanced filtering, sorting, searching, and pagination
func (r *MockClientCategoryRepository) GetClientCategoryListPageData(
	ctx context.Context,
	req *clientcategorypb.GetClientCategoryListPageDataRequest,
) (*clientcategorypb.GetClientCategoryListPageDataResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("get client_category list page data request is required")
	}

	r.mutex.RLock()
	defer r.mutex.RUnlock()

	// Convert map to slice of client_categories
	clientcategories := make([]*clientcategorypb.ClientCategory, 0, len(r.clientCategoriesByKey))
	for _, clientcategory := range r.clientCategoriesByKey {
		clientcategories = append(clientcategories, clientcategory)
	}

	// Use the list data processor to handle filtering, sorting, searching, and pagination
	result, err := r.processor.ProcessListRequest(
		clientcategories,
		req.Pagination,
		req.Filters,
		req.Sort,
		req.Search,
	)
	if err != nil {
		return nil, fmt.Errorf("failed to process client_category list data: %w", err)
	}

	// Convert processed items back to client_category protobuf format
	processedClientCategories := make([]*clientcategorypb.ClientCategory, len(result.Items))
	for i, item := range result.Items {
		if clientcategory, ok := item.(*clientcategorypb.ClientCategory); ok {
			processedClientCategories[i] = clientcategory
		} else {
			return nil, fmt.Errorf("failed to convert item to client_category type")
		}
	}

	// Convert search results to protobuf format
	searchResults := make([]*commonpb.SearchResult, len(result.SearchResults))
	for i, searchResult := range result.SearchResults {
		searchResults[i] = &commonpb.SearchResult{
			Score:      searchResult.Score,
			Highlights: searchResult.Highlights,
		}
	}

	return &clientcategorypb.GetClientCategoryListPageDataResponse{
		ClientCategoryList: processedClientCategories,
		Pagination:          result.PaginationResponse,
		SearchResults:       searchResults,
		Success:             true,
	}, nil
}

// GetClientCategoryItemPageData retrieves a single client_category with enhanced item page data
func (r *MockClientCategoryRepository) GetClientCategoryItemPageData(
	ctx context.Context,
	req *clientcategorypb.GetClientCategoryItemPageDataRequest,
) (*clientcategorypb.GetClientCategoryItemPageDataResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("get client_category item page data request is required")
	}
	if req.ClientCategoryId == "" {
		return nil, fmt.Errorf("client_category ID is required")
	}

	r.mutex.RLock()
	defer r.mutex.RUnlock()

	// Check in-memory store
	clientcategory, exists := r.clientCategories[req.ClientCategoryId]
	if !exists {
		return nil, fmt.Errorf("client_category with ID '%s' not found", req.ClientCategoryId)
	}

	// In a real implementation, you might:
	// 1. Load related data (client details, category details)
	// 2. Apply access control checks
	// 3. Format data for optimal frontend consumption
	// 4. Add audit logging

	return &clientcategorypb.GetClientCategoryItemPageDataResponse{
		ClientCategory: clientcategory,
		Success:        true,
	}, nil
}

// mapToProtobufClientCategory converts raw mock data to protobuf ClientCategory
func (r *MockClientCategoryRepository) mapToProtobufClientCategory(rawClientCategory map[string]any) (*clientcategorypb.ClientCategory, error) {
	clientCategory := &clientcategorypb.ClientCategory{}

	// Map ID field (for test compatibility)
	if id, ok := rawClientCategory["id"].(string); ok {
		clientCategory.Id = id
	}

	// Map required fields
	if clientId, ok := rawClientCategory["clientId"].(string); ok {
		clientCategory.ClientId = clientId
	} else {
		return nil, fmt.Errorf("missing or invalid clientId field")
	}

	if categoryId, ok := rawClientCategory["categoryId"].(string); ok {
		clientCategory.CategoryId = categoryId
	} else {
		return nil, fmt.Errorf("missing or invalid categoryId field")
	}

	// Map active status
	if active, ok := rawClientCategory["active"].(bool); ok {
		clientCategory.Active = active
	} else {
		clientCategory.Active = true // Default to active
	}

	// Handle date fields - convert string timestamps to Unix timestamps
	if dateCreated, ok := rawClientCategory["dateCreated"].(string); ok {
		clientCategory.DateCreatedString = &dateCreated
		if timestamp, err := r.parseTimestamp(dateCreated); err == nil {
			clientCategory.DateCreated = &timestamp
		}
	}

	if dateModified, ok := rawClientCategory["dateModified"].(string); ok {
		clientCategory.DateModifiedString = &dateModified
		if timestamp, err := r.parseTimestamp(dateModified); err == nil {
			clientCategory.DateModified = &timestamp
		}
	}

	return clientCategory, nil
}

// parseTimestamp converts string timestamp to Unix timestamp
func (r *MockClientCategoryRepository) parseTimestamp(timestampStr string) (int64, error) {
	// Direct timestamp parsing (already in milliseconds)
	if timestamp, err := strconv.ParseInt(timestampStr, 10, 64); err == nil {
		return timestamp, nil
	}

	// RFC3339 parsing converted to milliseconds
	if t, err := time.Parse(time.RFC3339, timestampStr); err == nil {
		return t.UnixMilli(), nil // Consistent milliseconds
	}

	// Try parsing as other common formats
	formats := []string{
		"2006-01-02T15:04:05Z",
		"2006-01-02 15:04:05",
		"2006-01-02T15:04:05.000Z",
	}

	for _, format := range formats {
		if t, err := time.Parse(format, timestampStr); err == nil {
			return t.UnixMilli(), nil // Consistent milliseconds
		}
	}

	return 0, fmt.Errorf("unable to parse timestamp: %s", timestampStr)
}

// NewClientCategoryRepository creates a new client_category repository - Provider interface compatibility
func NewClientCategoryRepository(businessType string) clientcategorypb.ClientCategoryDomainServiceServer {
	return NewMockClientCategoryRepository(businessType)
}

func init() {
	registry.RegisterRepositoryFactory("mock", "client_category", func(conn any, tableName string) (any, error) {
		businessType, _ := conn.(string)
		if businessType == "" {
			businessType = "education"
		}
		return NewMockClientCategoryRepository(businessType), nil
	})
}
